
# html lang
language: en

# main menu navigation
menu:
  Home: /
  Categories: /categories
  Tags: /tags
  Archives: /archives

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/broadbean.css

# scripts loaded in the end of the body
scripts:
- /js/broadbean.js

# use post description instead post excerpt
excerpt_description: true

# local search
local_search: false
  
